{% set version = "3.2.3" %}

package:
  name: dasel
  version: {{ version }}

source:
  folder: src/dasel
  url: https://github.com/TomWright/dasel/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 45351c07993e6c472eaa1231f30b61e927b1295f34063e4228d8dd7ff75ce538

build:
  number: 0
  script:
    - cd src/dasel
    - go build -o "${PREFIX}/bin/dasel"    -v -ldflags "-X github.com/tomwright/dasel/v3/internal.Version=v{{ version }}" ./cmd/dasel  # [not win]
    - go build -o "%PREFIX%\bin\dasel.exe" -v -ldflags "-X github.com/tomwright/dasel/v3/internal.Version=v{{ version }}" ./cmd/dasel  # [win]
    # Because osx-arm is cross-compiled, the following results in "bad CPU type in executable" if not disabled.
    - go test -v  # [not arm64]
    - go-licenses save . --save_path=license-files

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - dasel version
    - dasel --help
    # Skip the version check on Windows since grep doesn't work.
    - dasel version | grep v{{ version }}  # [not win]

about:
  home: https://github.com/TomWright/dasel
  license: MIT
  license_file:
    - src/dasel/LICENSE
    - src/dasel/license-files/
  summary: |
    Dasel (short for data-selector) allows you to query and modify data structures
    using selector strings.
  description: |
    Select, put and delete data from JSON, TOML, YAML, XML and CSV files with a single
    tool. Supports conversion between formats and can be used as a Go package.
  dev_url: https://github.com/TomWright/dasel

extra:
  recipe-maintainers:
    - tomwright
    - maresb
