schema_version: 1

context:
  version: "3.8.0"

package:
  name: dasel
  version: ${{ version }}

source:
  - url: https://github.com/TomWright/dasel/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 4d09e057c379d9d629e076752bf9ab9f7fab7a48712da4b73a655ea5157246b2
    target_directory: src/dasel
  # Windows-only dep `go-localereader` (MIT-licensed) misses standard license file layout,
  # so we have to manually add the license file
  - url: https://raw.githubusercontent.com/mattn/go-localereader/master/LICENSE
    sha256: dceede03550621e65ec7b79fcba87cf6dbb9d31132a8ae71a8fe8ceec0af7da3
    target_directory: library_licenses_2/github.com/go-localereader

build:
  number: 1
  script:
    - cd src/dasel
    - if: unix
      then: go build -o "${PREFIX}/bin/dasel"     -v -trimpath -ldflags "-s -w -X github.com/tomwright/dasel/v3/internal.Version=v${{ version }}" ./cmd/dasel
    - if: win
      then: go build -o "%LIBRARY_BIN%\dasel.exe" -v -trimpath -ldflags "-s -w -X github.com/tomwright/dasel/v3/internal.Version=v${{ version }}" ./cmd/dasel
    - go-licenses save ./cmd/dasel --save_path=library_licenses --ignore github.com/mattn/go-localereader

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - dasel --help
      - dasel version
      - if: not win
        then: dasel version | grep v${{ version }}
  - package_contents:
      bin:
        - dasel
      strict: true

about:
  license: MIT
  license_file:
    - src/dasel/LICENSE
    - src/dasel/library_licenses/
  summary: |
    Dasel (short for data-selector) allows you to query and modify data structures
    using selector strings.
  description: |
    Select, put and delete data from JSON, TOML, YAML, XML and CSV files with a single
    tool. Supports conversion between formats and can be used as a Go package.
  homepage: https://daseldocs.tomwright.me
  repository: https://github.com/TomWright/dasel

extra:
  recipe-maintainers:
    - tomwright
    - maresb
