schema_version: 1

context:
  version: "3.8.1"

package:
  name: dasel
  version: ${{ version }}

source:
  - url: https://github.com/TomWright/dasel/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 92711ddecfad9a1e97a41011d12ea88e9bb3c37827e5d5a718c3a8e8eaa88eaa
    target_directory: src/dasel
  # Windows-only dep `go-localereader` (MIT-licensed) misses standard license file layout,
  # so we have to manually add the license file
  - url: https://raw.githubusercontent.com/mattn/go-localereader/master/LICENSE
    sha256: dceede03550621e65ec7b79fcba87cf6dbb9d31132a8ae71a8fe8ceec0af7da3
    target_directory: library_licenses_2/github.com/go-localereader

build:
  number: 0
  script:
    - cd src/dasel
    - if: unix
      then:
        - go build -o "$PREFIX/bin/dasel"     -v -trimpath -ldflags "-s -w -X github.com/tomwright/dasel/v3/internal.Version=v${{ version }}" ./cmd/dasel
        # generate manpage and shell completions
        - mkdir -p "$PREFIX/share/man/man1" "$PREFIX/share/bash-completion/completions" "$PREFIX/share/fish/vendor_completions.d" "$PREFIX/share/zsh/site-functions"
        - '"$PREFIX/bin/dasel" man             > "$PREFIX/share/man/man1/dasel.1"'
        - '"$PREFIX/bin/dasel" completion bash > "$PREFIX/share/bash-completion/completions/dasel"'
        - '"$PREFIX/bin/dasel" completion fish > "$PREFIX/share/fish/vendor_completions.d/dasel.fish"'
        - '"$PREFIX/bin/dasel" completion zsh  > "$PREFIX/share/zsh/site-functions/_dasel"'
    - if: win
      then:
        - go build -o "%LIBRARY_BIN%\dasel.exe" -v -trimpath -ldflags "-s -w -X github.com/tomwright/dasel/v3/internal.Version=v${{ version }}" ./cmd/dasel
        # generate manpage and shell completions
        - mkdir "%LIBRARY_PREFIX%\share\man\man1"
        - mkdir "%LIBRARY_PREFIX%\share\bash-completion\completions"
        - mkdir "%LIBRARY_PREFIX%\share\fish\vendor_completions.d"
        - mkdir "%LIBRARY_PREFIX%\share\zsh\site-functions"
        - '"%LIBRARY_BIN%\dasel.exe" man             > "%LIBRARY_PREFIX%\share\man\man1\dasel.1"'
        - '"%LIBRARY_BIN%\dasel.exe" completion bash > "%LIBRARY_PREFIX%\share\bash-completion\completions\dasel"'
        - '"%LIBRARY_BIN%\dasel.exe" completion fish > "%LIBRARY_PREFIX%\share\fish\vendor_completions.d\dasel.fish"'
        - '"%LIBRARY_BIN%\dasel.exe" completion zsh  > "%LIBRARY_PREFIX%\share\zsh\site-functions\_dasel"'
    - go-licenses save ./cmd/dasel --save_path=library_licenses --ignore github.com/mattn/go-localereader

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - dasel --help
      - dasel version
      - if: not win
        then: dasel version | grep v${{ version }}
  - package_contents:
      bin:
        - dasel
      files:
        - if: unix
          then:
            - share/man/man1/dasel.1
            - share/bash-completion/completions/dasel
            - share/fish/vendor_completions.d/dasel.fish
            - share/zsh/site-functions/_dasel
        - if: win
          then:
            - Library/share/man/man1/dasel.1
            - Library/share/bash-completion/completions/dasel
            - Library/share/fish/vendor_completions.d/dasel.fish
            - Library/share/zsh/site-functions/_dasel
      strict: true

about:
  license: MIT
  license_file:
    - src/dasel/LICENSE
    - src/dasel/library_licenses/
  summary: |
    Dasel (short for data-selector) allows you to query and modify data structures
    using selector strings.
  description: |
    Select, put and delete data from JSON, TOML, YAML, XML and CSV files with a single
    tool. Supports conversion between formats and can be used as a Go package.
  homepage: https://daseldocs.tomwright.me
  repository: https://github.com/TomWright/dasel

extra:
  recipe-maintainers:
    - salim-b
    - tomwright
    - maresb
